### ISSUE TITLE
Local connector should exclude paths that match `.gitignore`

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev#49]
By default, `node_modules` etc. appear in the editor; we should prevent paths matching `.gitignore` patterns from being included by default.

![image](https://user-images.githubusercontent.com/646525/127367305-be8337d8-922e-4931-9ce8-68f13c73b4fa.png)

**Comment by Zoramite** [comment]
Specifically this applies to the local project connector since the github/other service connectors would not have files that have been git ignored.
